# 创建张量 tensor

张量是一种专门的数据结构，与数组和矩阵非常相似。 在 PyTorch 中，我们使用张量对模型的输入和输出以及模型的参数进行编码。
张量类似于 NumPy 的 ndarrays，不同之处在于张量可以在 GPU 或其他硬件加速器上运行。

In [3]:

import numpy as np
import torch

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)
x_data.shape

tensor([[1, 2],
        [3, 4]])


In [24]:

######################################################################
# **From a NumPy array**
#
# Tensors can be created from NumPy arrays (and vice versa - see :ref:`bridge-to-np-label`).
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [26]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7861, 0.8576],
        [0.5587, 0.6428]]) 

Random Tensor: 
 tensor([[1, 2],
        [3, 4]]) 



一下创建的都是浮点数

In [13]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor.dtype)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

torch.float32
Random Tensor: 
 tensor([[0.6293, 0.8525, 0.5467],
        [0.6156, 0.0465, 0.6240]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
tensor = torch.ones(4, 4)
print(f"第一行: {tensor[0]}")
print(f"第一列: {tensor[:, 0]}")
print(f"最后一列: {tensor[..., -1]}")
tensor[:, 1] = 0  #第二列等于0
print(tensor)

######################################################################
# 拼接  dim表示维度，如果为0，表示行会改变，如果为1表示列会改变
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

第一行: tensor([1., 1., 1., 1.])
第一列: tensor([1., 1., 1., 1.])
最后一列: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# Tensor 相乘

## 点积 torch.dot
是 PyTorch 中用于计算两个一维张量（向量）点积（内积）的函数

a·b = a₁*b₁ + a₂*b₂ + ... + aₙ*bₙ。
输入张量必须是一维的，若为多维张量需先展平（如 flatten()）

## 矩阵乘积 torch.matmul/@

m×n @ n×K=m×k

## 元素按位相乘 ×
要求两个向量维度相同
m×n × m×n =m×n

In [14]:
tensor1 = torch.tensor([[1., 2., 3.], [1., 2., 3.]])
tensor3 = torch.tensor([[1., 2., 3.], [1., 2., 3.]])
print(tensor1.shape)
tensor2 = torch.ones(3, 1)
print(tensor1)
print(tensor2)
print(torch.matmul(tensor1, tensor2))
print(tensor1 @ tensor2)
# print(tensor1 * tensor2)  #必须为对应元素相乘
print(tensor1 * tensor3)  #必须为对应元素相乘
torch.mul(tensor1, tensor3)

#
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))  #仅支持一维向量 tensor1



torch.Size([2, 3])
tensor([[1., 2., 3.],
        [1., 2., 3.]])
tensor([[1.],
        [1.],
        [1.]])
tensor([[6.],
        [6.]])
tensor([[6.],
        [6.]])
tensor([[1., 4., 9.],
        [1., 4., 9.]])


tensor(7)

In [23]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x  # 构建计算图，记录 y = x² + 3x
y.backward()
print(x.grad)

tensor(7.)


# item

将此张量的值作为标准 Python 数字返回。这对于具有一个元素的张量有效

In [3]:
x = torch.tensor([1.0])
x.item()

1.0

# backward


计算给定张量相对于图的叶子节点的梯度之和，因此最后要调用sum函数

 tensor参数 requires_grad=True

 grad can be implicitly created only for scalar outputs

In [17]:

x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = (x.pow(2) + x * 3 + 5).sum()
print(out.item())
out.backward()
x.grad

30.0


tensor([[5., 1.],
        [5., 5.]])