# 创建张量 tensor

In [4]:

import numpy as np
import torch

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [24]:

######################################################################
# **From a NumPy array**
#
# Tensors can be created from NumPy arrays (and vice versa - see :ref:`bridge-to-np-label`).
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [26]:
x_ones = torch.ones_like(x_data)  # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7861, 0.8576],
        [0.5587, 0.6428]]) 

Random Tensor: 
 tensor([[1, 2],
        [3, 4]]) 



In [8]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1011, 0.7708, 0.8580],
        [0.5389, 0.2374, 0.1538]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
tensor = torch.ones(4, 4)
print(f"第一行: {tensor[0]}")
print(f"第一列: {tensor[:, 0]}")
print(f"最后一列: {tensor[..., -1]}")
tensor[:, 1] = 0  #第二列等于0
print(tensor)

######################################################################
# 拼接  dim表示维度，如果为0，表示行会改变，如果为1表示列会改变
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

第一行: tensor([1., 1., 1., 1.])
第一列: tensor([1., 1., 1., 1.])
最后一列: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# Tensor 相乘

In [37]:
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
print(tensor1)
print(tensor2)
print(torch.matmul(tensor1, tensor2))


tensor([[ 0.2977,  1.4110, -0.7603,  0.2307],
        [-0.4320,  1.8075,  0.2994,  0.1867],
        [ 0.6009,  1.9932,  2.0223,  0.5226]])
tensor([-0.6514, -2.3982, -0.2400, -0.1177])
tensor([-3.4224, -4.1472, -5.7184])


In [39]:

# 对应位置元素相乘
tensor3 = torch.randn(2, 2)
tensor4 = torch.randn(2, 2)
print(tensor3)
print(tensor4)
print("mul ", tensor3.mul(tensor4))
print("* ", tensor3 * tensor4)

tensor([[-0.3071, -0.3253],
        [-1.3880, -0.1785]])
tensor([[-0.2701, -0.7858],
        [ 1.1426, -0.1985]])
mul  tensor([[ 0.0830,  0.2556],
        [-1.5859,  0.0354]])
*  tensor([[ 0.0830,  0.2556],
        [-1.5859,  0.0354]])


In [23]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3 * x  # 构建计算图，记录 y = x² + 3x
y.backward()
print(x.grad)

tensor(7.)
