import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(type(a))

In [4]:
import numpy as np

a = np.array([2, 3, 4])
print(a)
print()
# a = np.array(1, 2, 3, 4) 这种创建是错误的
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
print()

c = np.array([[1, 2], [3, 4]], dtype=complex)
print(c)
# [[1.+0.j 2.+0.j]
# [3.+0.j 4.+0.j]]

print(np.zeros((3, 4)))  # 零矩阵
# [[0. 0. 0. 0.]
# [0. 0. 0. 0.]
# [0. 0. 0. 0.]]
print(np.ones((2, 3, 4), dtype=np.int16), end="\n")  # 单位矩阵,2个3行4列的单位矩阵
#  [[[1 1 1 1]
#   [1 1 1 1]
#   [1 1 1 1]]
# 
#  [[1 1 1 1]
#   [1 1 1 1]
#   [1 1 1 1]]]
print(np.empty((2, 3)))  # 空矩阵
# [[1.39069238e-309 1.39069238e-309 1.39069238e-309]
# [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
print(np.arange(10, 30, 5))  # 没有最后一个
# [10 15 20 25]
print(np.arange(0, 2, 0.3))  # 接受浮点数
# [0.  0.3 0.6 0.9 1.2 1.5 1.8]
print(np.linspace(0, 2, 9))  # 分成9份，(b-a)/8
# [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


[2 3 4]

[[1.5 2.  3. ]
 [4.  5.  6. ]]

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [3]:
import numpy as np

a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)  # [20 30 40 50]
print(b)  # [0 1 2 3]
print(b - a)  # [-20 -29 -38 -47]
print(b ** 2)  # [0 1 4 9]
print(10 * np.sin(a))  # [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
print(a < 35)  # [ True  True False False]

######################
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A * B)  # 对应元素相乘,[[2 0] [0 4]]
print(A @ B)  # 矩阵点积，[[5 4] [3 4]]
print(A.dot(B))  # 矩阵点积，[[5 4] [3 4]]


[20 30 40 50]
[0 1 2 3]
[-20 -29 -38 -47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
