# 创建dataFrame

In [255]:
import pandas as pd
import numpy as np
dates = pd.date_range("20130101", periods=6)
print(dates)
print("- "*50)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                   A         B         C         D
2013-01-01 -1.902578 -1.049960 -0.755687 -1.261681
2013-01-02  1.371784 -0.447580  1.146231 -1.398147
2013-01-03 -0.529472  0.229024 -2.385101 -0.832358
2013-01-04 -0.538858 -0.298062  1.180761  0.905542
2013-01-05 -1.562485 -0.034475  0.260163 -0.487132
2013-01-06 -0.045748  0.229686 -1.341456  0.424127


## 基本属性

In [256]:
print(df.head())

                   A         B         C         D
2013-01-01 -1.902578 -1.049960 -0.755687 -1.261681
2013-01-02  1.371784 -0.447580  1.146231 -1.398147
2013-01-03 -0.529472  0.229024 -2.385101 -0.832358
2013-01-04 -0.538858 -0.298062  1.180761  0.905542
2013-01-05 -1.562485 -0.034475  0.260163 -0.487132


默认后5行

In [257]:
print(df.tail())

                   A         B         C         D
2013-01-02  1.371784 -0.447580  1.146231 -1.398147
2013-01-03 -0.529472  0.229024 -2.385101 -0.832358
2013-01-04 -0.538858 -0.298062  1.180761  0.905542
2013-01-05 -1.562485 -0.034475  0.260163 -0.487132
2013-01-06 -0.045748  0.229686 -1.341456  0.424127


索引

In [258]:
print(df.index)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


转置

In [259]:
print(df.T)

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.902578    1.371784   -0.529472   -0.538858   -1.562485   -0.045748
B   -1.049960   -0.447580    0.229024   -0.298062   -0.034475    0.229686
C   -0.755687    1.146231   -2.385101    1.180761    0.260163   -1.341456
D   -1.261681   -1.398147   -0.832358    0.905542   -0.487132    0.424127


In [260]:
print(df.columns)

Index(['A', 'B', 'C', 'D'], dtype='object')


数据转换

In [261]:

print(df.to_numpy())

[[-1.90257848 -1.04996028 -0.75568676 -1.26168072]
 [ 1.37178399 -0.4475804   1.14623104 -1.3981469 ]
 [-0.52947248  0.22902367 -2.3851007  -0.8323583 ]
 [-0.53885811 -0.2980623   1.18076129  0.90554156]
 [-1.56248508 -0.03447505  0.26016321 -0.48713246]
 [-0.04574806  0.22968642 -1.34145608  0.42412654]]


排序

In [262]:
print(df.sort_values(by="B"))

                   A         B         C         D
2013-01-01 -1.902578 -1.049960 -0.755687 -1.261681
2013-01-02  1.371784 -0.447580  1.146231 -1.398147
2013-01-04 -0.538858 -0.298062  1.180761  0.905542
2013-01-05 -1.562485 -0.034475  0.260163 -0.487132
2013-01-03 -0.529472  0.229024 -2.385101 -0.832358
2013-01-06 -0.045748  0.229686 -1.341456  0.424127


快速计算指标

In [263]:
print(df.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.534560 -0.228561 -0.315848 -0.441608
std    1.166296  0.486732  1.430835  0.928068
min   -1.902578 -1.049960 -2.385101 -1.398147
25%   -1.306578 -0.410201 -1.195014 -1.154350
50%   -0.534165 -0.166269 -0.247762 -0.659745
75%   -0.166679  0.163149  0.924714  0.196312
max    1.371784  0.229686  1.180761  0.905542


# 查询数据

按照列选择

In [264]:
print(df["A"])

2013-01-01   -1.902578
2013-01-02    1.371784
2013-01-03   -0.529472
2013-01-04   -0.538858
2013-01-05   -1.562485
2013-01-06   -0.045748
Freq: D, Name: A, dtype: float64


In [265]:
print(df[0:3])      #按照行选择

                   A         B         C         D
2013-01-01 -1.902578 -1.049960 -0.755687 -1.261681
2013-01-02  1.371784 -0.447580  1.146231 -1.398147
2013-01-03 -0.529472  0.229024 -2.385101 -0.832358


loc函数来选择数据

In [266]:
print(df.loc[dates[0:2]])       #选择2行
print(df.loc[:, ["A", "B"]])        #所有行，ab两列

                   A        B         C         D
2013-01-01 -1.902578 -1.04996 -0.755687 -1.261681
2013-01-02  1.371784 -0.44758  1.146231 -1.398147
                   A         B
2013-01-01 -1.902578 -1.049960
2013-01-02  1.371784 -0.447580
2013-01-03 -0.529472  0.229024
2013-01-04 -0.538858 -0.298062
2013-01-05 -1.562485 -0.034475
2013-01-06 -0.045748  0.229686


In [267]:
print(df.iloc[[1, 2, 4], [0, 2]])       #通过位置进行选择

                   A         C
2013-01-02  1.371784  1.146231
2013-01-03 -0.529472 -2.385101
2013-01-05 -1.562485  0.260163


In [268]:
print(df[df["A"] > 0])      #布尔进行选择

                   A        B         C         D
2013-01-02  1.371784 -0.44758  1.146231 -1.398147


赋值

In [269]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130102', periods=6))
df["F"] = s1
df.at[dates[0], "A"] = 0
df.iat[0, 1] = 0
df.loc[:, "D"] = np.array([5] * len(df))
print(df)

                   A         B         C  D    F
2013-01-01  0.000000  0.000000 -0.755687  5  NaN
2013-01-02  1.371784 -0.447580  1.146231  5  1.0
2013-01-03 -0.529472  0.229024 -2.385101  5  2.0
2013-01-04 -0.538858 -0.298062  1.180761  5  3.0
2013-01-05 -1.562485 -0.034475  0.260163  5  4.0
2013-01-06 -0.045748  0.229686 -1.341456  5  5.0


重建索引（reindex）可以更改、添加、删除指定轴的索引，并返回数据副本，即不更改原数据。

In [270]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
print(df1)
print(df1.dropna(how='any'))        #不会改变df1
print(df1.fillna(value=5))      #填充缺失值

                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000 -0.755687  5  NaN  1.0
2013-01-02  1.371784 -0.447580  1.146231  5  1.0  1.0
2013-01-03 -0.529472  0.229024 -2.385101  5  2.0  NaN
2013-01-04 -0.538858 -0.298062  1.180761  5  3.0  NaN
                   A        B         C  D    F    E
2013-01-02  1.371784 -0.44758  1.146231  5  1.0  1.0
                   A         B         C  D    F    E
2013-01-01  0.000000  0.000000 -0.755687  5  5.0  1.0
2013-01-02  1.371784 -0.447580  1.146231  5  1.0  1.0
2013-01-03 -0.529472  0.229024 -2.385101  5  2.0  5.0
2013-01-04 -0.538858 -0.298062  1.180761  5  3.0  5.0
